/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.CTRLAvion;
import Controller.CTRLAerolinea;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Carlos
 */
public class FormAviones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormAviones.class.getName());

    CTRLAvion ctrl;
    CTRLAerolinea ctrlAerolinea;
    /**
     * Creates new form FormAviones
     */
    public FormAviones() {
        initComponents();
        ctrl = new CTRLAvion();
        ctrlAerolinea = new CTRLAerolinea();
        ctrl.mostrarAviones(jTable1);
        ctrlAerolinea.cargarComboBox(comboAerolinea);
        jTable1.setDefaultEditor(Object.class, null);
        this.setLocationRelativeTo(null);
        configurarEventosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAgg = new javax.swing.JButton();
        btnEd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnVol = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtCapa = new javax.swing.JTextField();
        comboAerolinea = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Aviones");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Modelo", "Capacidad", "Aerolinea"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAgg.setText("Agregar");
        btnAgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggActionPerformed(evt);
            }
        });

        btnEd.setText("Editar");
        btnEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdActionPerformed(evt);
            }
        });

        btnDel.setText("Eliminar");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnVol.setText("Volver");
        btnVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolActionPerformed(evt);
            }
        });

        jLabel2.setText("Modelo");

        jLabel3.setText("Capacidad");

        jLabel4.setText("Aerolínea");

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        txtCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapaActionPerformed(evt);
            }
        });

        comboAerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAerolineaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnAgg)
                        .addGap(165, 165, 165)
                        .addComponent(btnEd)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVol))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboAerolinea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgg)
                    .addComponent(btnEd)
                    .addComponent(btnDel)
                    .addComponent(btnVol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggActionPerformed

    if (!validarCampos()) {
        return;
    }
    
    try {
        ctrl.agregar(txtModel, txtCapa, comboAerolinea);
        ctrl.mostrarAviones(jTable1);
        limpiarCampos();
        txtModel.requestFocus();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al agregar avión: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAggActionPerformed

    private void btnVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolActionPerformed
        MenuPrincipal MP = new MenuPrincipal();
        MP.setVisible(true);
        MP.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVolActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
    int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un avión para eliminar");
        return;
    }
    int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Está seguro de eliminar este avión?", 
        "Confirmar eliminación", 
        JOptionPane.YES_NO_OPTION
    );
    
    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            int idAvion = (int) jTable1.getValueAt(filaSeleccionada, 0);
            ctrl.eliminar(idAvion);
            ctrl.mostrarAviones(jTable1);
            limpiarCampos();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar avión: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdActionPerformed
    int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un avión para editar");
        return;
    }
    if (!validarCampos()) {
        return;
    }
    
    try {
        int idAvion = (int) jTable1.getValueAt(filaSeleccionada, 0);
        ctrl.actualizar(idAvion, txtModel, txtCapa, comboAerolinea);
        ctrl.mostrarAviones(jTable1);
        limpiarCampos();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar avión: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEdActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
    txtCapa.requestFocus();
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapaActionPerformed
    comboAerolinea.requestFocus();
    }//GEN-LAST:event_txtCapaActionPerformed

    private void comboAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAerolineaActionPerformed
    if (!txtModel.getText().trim().isEmpty() && !txtCapa.getText().trim().isEmpty()) {
        if (validarCampos()) {
            btnAggActionPerformed(evt);
        }
    }
    }//GEN-LAST:event_comboAerolineaActionPerformed

    private boolean validarCampos() {
    if (txtModel.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "El modelo no puede estar vacío");
        txtModel.requestFocus();
        return false;
    }
    
    if (txtCapa.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "La capacidad no puede estar vacía");
        txtCapa.requestFocus();
        return false;
    }
    
    if (comboAerolinea.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una aerolínea");
        comboAerolinea.requestFocus();
        return false;
    }
    try {
        int capacidad = Integer.parseInt(txtCapa.getText().trim());
        if (capacidad <= 0) {
            JOptionPane.showMessageDialog(this, "La capacidad debe ser un número positivo");
            txtCapa.requestFocus();
            return false;
        }
        if (capacidad > 1000) {
            JOptionPane.showMessageDialog(this, "La capacidad no puede ser mayor a 1000 pasajeros");
            txtCapa.requestFocus();
            return false;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La capacidad debe ser un número válido");
        txtCapa.requestFocus();
        return false;
    }
    
    return true;
}

private void limpiarCampos() {
    txtModel.setText("");
    txtCapa.setText("");
    if (comboAerolinea.getItemCount() > 0) {
        comboAerolinea.setSelectedIndex(0);
    }
    jTable1.clearSelection();
}

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
    int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada != -1) {
        txtModel.setText(jTable1.getValueAt(filaSeleccionada, 1).toString());
        txtCapa.setText(jTable1.getValueAt(filaSeleccionada, 2).toString());
        int idAerolineaSeleccionada = (int) jTable1.getValueAt(filaSeleccionada, 3);
        for (int i = 0; i < comboAerolinea.getItemCount(); i++) {
            String item = comboAerolinea.getItemAt(i);
            if (item != null && item.contains(" - ")) {
                int idAerolinea = Integer.parseInt(item.split(" - ")[0]);
                if (idAerolinea == idAerolineaSeleccionada) {
                    comboAerolinea.setSelectedIndex(i);
                    break;
                }
            }
        }
    }
}

private void configurarEventosTabla() {
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
}
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgg;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEd;
    private javax.swing.JButton btnVol;
    private javax.swing.JComboBox<String> comboAerolinea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCapa;
    private javax.swing.JTextField txtModel;
    // End of variables declaration//GEN-END:variables
}
