/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Luis Carlos
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAero = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAeroli = new javax.swing.JButton();
        btnavi = new javax.swing.JButton();
        btnvue = new javax.swing.JButton();
        btnpas = new javax.swing.JButton();
        btnres = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        btnAero.setBackground(new java.awt.Color(51, 153, 255));
        btnAero.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btnAero.setText("Aeropuertos");
        btnAero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAeroActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnAeroli.setBackground(new java.awt.Color(51, 153, 255));
        btnAeroli.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btnAeroli.setText("Aerolineas");
        btnAeroli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAeroliActionPerformed(evt);
            }
        });

        btnavi.setBackground(new java.awt.Color(51, 153, 255));
        btnavi.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btnavi.setText("Aviones");
        btnavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaviActionPerformed(evt);
            }
        });

        btnvue.setBackground(new java.awt.Color(51, 153, 255));
        btnvue.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btnvue.setText("Vuelos");
        btnvue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvueActionPerformed(evt);
            }
        });

        btnpas.setBackground(new java.awt.Color(51, 153, 255));
        btnpas.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btnpas.setText("Pasajeros");
        btnpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpasActionPerformed(evt);
            }
        });

        btnres.setBackground(new java.awt.Color(51, 153, 255));
        btnres.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btnres.setText("Reservas");
        btnres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnvue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(193, 193, 193)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnpas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAeroli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnavi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAeroli, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnavi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnvue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnres, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE GESTIÓN DE VUELOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAeroliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAeroliActionPerformed
        FormAerolineas AE = new FormAerolineas();
        AE.setVisible(true);
        AE.setLocationRelativeTo(null);
        this.dispose();   
    }//GEN-LAST:event_btnAeroliActionPerformed

    private void btnaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaviActionPerformed
        FormAviones AV = new FormAviones();
        AV.setVisible(true);
        AV.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnaviActionPerformed

    private void btnvueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvueActionPerformed
        FormVuelos FV = new FormVuelos();
        FV.setVisible(true);
        FV.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnvueActionPerformed

    private void btnpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpasActionPerformed
        FormPasajeros FP = new FormPasajeros();
        FP.setVisible(true);
        FP.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnpasActionPerformed

    private void btnresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresActionPerformed
        FormReservas FR = new FormReservas();
        FR.setVisible(true);
        FR.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnresActionPerformed

    private void btnAeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAeroActionPerformed
        FormAeropuertos AP = new FormAeropuertos();
        AP.setVisible(true);
        AP.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnAeroActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAero;
    private javax.swing.JButton btnAeroli;
    private javax.swing.JButton btnavi;
    private javax.swing.JButton btnpas;
    private javax.swing.JButton btnres;
    private javax.swing.JButton btnvue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
